# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Grade_Calc(object):
    def setupUi(self, Grade_Calc):
        Grade_Calc.setObjectName("Grade_Calc")
        Grade_Calc.resize(350, 300)
        Grade_Calc.setMinimumSize(QtCore.QSize(350, 300))
        Grade_Calc.setMaximumSize(QtCore.QSize(350, 300))
        self.centralwidget = QtWidgets.QWidget(parent=Grade_Calc)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(10, 10, 331, 121))
        self.menu.setReadOnly(True)
        self.menu.setObjectName("menu")
        self.label_total_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_total_score.setGeometry(QtCore.QRect(10, 190, 161, 16))
        self.label_total_score.setObjectName("label_total_score")
        self.grade_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.grade_button.setGeometry(QtCore.QRect(20, 220, 91, 21))
        self.grade_button.setObjectName("grade_button")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(20, 240, 91, 21))
        self.clear_button.setObjectName("clear_button")
        self.total_score = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.total_score.setGeometry(QtCore.QRect(180, 190, 131, 20))
        self.total_score.setObjectName("total_score")
        self.student_one_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.student_one_radio.setGeometry(QtCore.QRect(90, 160, 62, 14))
        self.student_one_radio.setChecked(True)
        self.student_one_radio.setObjectName("student_one_radio")
        self.student_two_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.student_two_radio.setGeometry(QtCore.QRect(120, 160, 62, 14))
        self.student_two_radio.setObjectName("student_two_radio")
        self.student_three_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.student_three_radio.setGeometry(QtCore.QRect(150, 160, 62, 14))
        self.student_three_radio.setObjectName("student_three_radio")
        self.student_four_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.student_four_radio.setGeometry(QtCore.QRect(180, 160, 62, 14))
        self.student_four_radio.setObjectName("student_four_radio")
        self.student_five_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.student_five_radio.setGeometry(QtCore.QRect(210, 160, 62, 14))
        self.student_five_radio.setObjectName("student_five_radio")
        self.total_score_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.total_score_2.setGeometry(QtCore.QRect(180, 210, 131, 20))
        self.total_score_2.setObjectName("total_score_2")
        self.total_score_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.total_score_3.setGeometry(QtCore.QRect(180, 230, 131, 20))
        self.total_score_3.setObjectName("total_score_3")
        self.total_score_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.total_score_4.setGeometry(QtCore.QRect(180, 250, 131, 20))
        self.total_score_4.setObjectName("total_score_4")
        self.total_score_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.total_score_5.setGeometry(QtCore.QRect(180, 270, 131, 20))
        self.total_score_5.setObjectName("total_score_5")
        self.label_total_score_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_total_score_2.setGeometry(QtCore.QRect(80, 140, 261, 16))
        self.label_total_score_2.setObjectName("label_total_score_2")
        Grade_Calc.setCentralWidget(self.centralwidget)

        self.retranslateUi(Grade_Calc)
        QtCore.QMetaObject.connectSlotsByName(Grade_Calc)

    def retranslateUi(self, Grade_Calc):
        _translate = QtCore.QCoreApplication.translate
        Grade_Calc.setWindowTitle(_translate("Grade_Calc", "Grade Calculator"))
        self.menu.setPlainText(_translate("Grade_Calc", "Please enter total number of students and their grade\n"
"\n"
"Enter grades as follows:\n"
"10 20 30 40 etc..."))
        self.label_total_score.setText(_translate("Grade_Calc", "Enter all scores for Students:"))
        self.grade_button.setText(_translate("Grade_Calc", "Grade"))
        self.clear_button.setText(_translate("Grade_Calc", "Clear"))
        self.student_one_radio.setText(_translate("Grade_Calc", "1"))
        self.student_two_radio.setText(_translate("Grade_Calc", "2"))
        self.student_three_radio.setText(_translate("Grade_Calc", "3"))
        self.student_four_radio.setText(_translate("Grade_Calc", "4"))
        self.student_five_radio.setText(_translate("Grade_Calc", "5"))
        self.label_total_score_2.setText(_translate("Grade_Calc", "Click the between 1 to 5 students:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Grade_Calc = QtWidgets.QMainWindow()
    ui = Ui_Grade_Calc()
    ui.setupUi(Grade_Calc)
    Grade_Calc.show()
    sys.exit(app.exec())
